server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
         - id: user-service-route
           uri: lb://user-service
           predicates:
             - Path=/api/v1/users/**
         - id: product-service-route
           uri: lb://product-service
           predicates:
             - Path=/api/v1/products/**
             - Path=/api/internal/v1/products/**
         - id: order-service-route
           uri: lb://order-service
           predicates:
             - Path=/api/v1/orders/**